// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAlertRules = `-- name: CountAlertRules :one
SELECT COUNT(*) FROM alert_rules WHERE organization_id = $1
`

func (q *Queries) CountAlertRules(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertRules, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled, last_triggered_at, created_at, updated_at
`

type CreateAlertRuleParams struct {
	OrganizationID  uuid.UUID      `json:"organization_id"`
	Name            string         `json:"name"`
	AlertType       string         `json:"alert_type"`
	Threshold       pgtype.Numeric `json:"threshold"`
	WindowMinutes   int32          `json:"window_minutes"`
	CooldownMinutes int32          `json:"cooldown_minutes"`
	NotifyRoles     []string       `json:"notify_roles"`
	Enabled         bool           `json:"enabled"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.OrganizationID,
		arg.Name,
		arg.AlertType,
		arg.Threshold,
		arg.WindowMinutes,
		arg.CooldownMinutes,
		arg.NotifyRoles,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AlertType,
		&i.Threshold,
		&i.WindowMinutes,
		&i.CooldownMinutes,
		&i.NotifyRoles,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1 AND organization_id = $2
`

type DeleteAlertRuleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, arg.ID, arg.OrganizationID)
	return err
}

const evaluateAvgLatency = `-- name: EvaluateAvgLatency :one
SELECT COALESCE(AVG(duration_ms), 0)::float8 AS avg_duration_ms
FROM spans
WHERE organization_id = $1
  AND created_at >= NOW() - ($2::int * interval '1 minute')
`

type EvaluateAvgLatencyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	WindowMinutes  int32     `json:"window_minutes"`
}

func (q *Queries) EvaluateAvgLatency(ctx context.Context, arg EvaluateAvgLatencyParams) (float64, error) {
	row := q.db.QueryRow(ctx, evaluateAvgLatency, arg.OrganizationID, arg.WindowMinutes)
	var avg_duration_ms float64
	err := row.Scan(&avg_duration_ms)
	return avg_duration_ms, err
}

const evaluateErrorSpike = `-- name: EvaluateErrorSpike :one
SELECT COUNT(*) AS error_count
FROM spans
WHERE organization_id = $1
  AND http_status >= 400
  AND created_at >= NOW() - ($2::int * interval '1 minute')
`

type EvaluateErrorSpikeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	WindowMinutes  int32     `json:"window_minutes"`
}

func (q *Queries) EvaluateErrorSpike(ctx context.Context, arg EvaluateErrorSpikeParams) (int64, error) {
	row := q.db.QueryRow(ctx, evaluateErrorSpike, arg.OrganizationID, arg.WindowMinutes)
	var error_count int64
	err := row.Scan(&error_count)
	return error_count, err
}

const evaluateFailureRate = `-- name: EvaluateFailureRate :one
SELECT
    COUNT(*) AS total_count,
    COUNT(*) FILTER (WHERE http_status >= 400) AS error_count
FROM spans
WHERE organization_id = $1
  AND created_at >= NOW() - ($2::int * interval '1 minute')
`

type EvaluateFailureRateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	WindowMinutes  int32     `json:"window_minutes"`
}

type EvaluateFailureRateRow struct {
	TotalCount int64 `json:"total_count"`
	ErrorCount int64 `json:"error_count"`
}

func (q *Queries) EvaluateFailureRate(ctx context.Context, arg EvaluateFailureRateParams) (EvaluateFailureRateRow, error) {
	row := q.db.QueryRow(ctx, evaluateFailureRate, arg.OrganizationID, arg.WindowMinutes)
	var i EvaluateFailureRateRow
	err := row.Scan(&i.TotalCount, &i.ErrorCount)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled, last_triggered_at, created_at, updated_at FROM alert_rules WHERE id = $1 AND organization_id = $2
`

type GetAlertRuleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetAlertRule(ctx context.Context, arg GetAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, arg.ID, arg.OrganizationID)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AlertType,
		&i.Threshold,
		&i.WindowMinutes,
		&i.CooldownMinutes,
		&i.NotifyRoles,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledAlertRulesByOrg = `-- name: GetEnabledAlertRulesByOrg :many
SELECT ar.id, ar.organization_id, ar.name, ar.alert_type, ar.threshold, ar.window_minutes, ar.cooldown_minutes, ar.notify_roles, ar.enabled, ar.last_triggered_at, ar.created_at, ar.updated_at FROM alert_rules ar
JOIN organizations o ON o.id = ar.organization_id
WHERE ar.enabled = TRUE AND o.plan != 'free' AND ar.organization_id = $1
ORDER BY ar.created_at
`

func (q *Queries) GetEnabledAlertRulesByOrg(ctx context.Context, organizationID uuid.UUID) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, getEnabledAlertRulesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AlertType,
			&i.Threshold,
			&i.WindowMinutes,
			&i.CooldownMinutes,
			&i.NotifyRoles,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledAlertRulesByOrgAndType = `-- name: GetEnabledAlertRulesByOrgAndType :many
SELECT id, organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled, last_triggered_at, created_at, updated_at FROM alert_rules
WHERE organization_id = $1 AND alert_type = $2 AND enabled = TRUE
`

type GetEnabledAlertRulesByOrgAndTypeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AlertType      string    `json:"alert_type"`
}

func (q *Queries) GetEnabledAlertRulesByOrgAndType(ctx context.Context, arg GetEnabledAlertRulesByOrgAndTypeParams) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, getEnabledAlertRulesByOrgAndType, arg.OrganizationID, arg.AlertType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AlertType,
			&i.Threshold,
			&i.WindowMinutes,
			&i.CooldownMinutes,
			&i.NotifyRoles,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberEmailsByRoles = `-- name: GetMemberEmailsByRoles :many
SELECT u.email, u.name
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
  AND m.role = ANY($2::text[])
`

type GetMemberEmailsByRolesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Roles          []string  `json:"roles"`
}

type GetMemberEmailsByRolesRow struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) GetMemberEmailsByRoles(ctx context.Context, arg GetMemberEmailsByRolesParams) ([]GetMemberEmailsByRolesRow, error) {
	rows, err := q.db.Query(ctx, getMemberEmailsByRoles, arg.OrganizationID, arg.Roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemberEmailsByRolesRow{}
	for rows.Next() {
		var i GetMemberEmailsByRolesRow
		if err := rows.Scan(&i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO alert_events (organization_id, alert_rule_id, payload)
VALUES ($1, $2, $3)
RETURNING id, organization_id, alert_rule_id, triggered_at, payload
`

type InsertAlertEventParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	AlertRuleID    uuid.UUID `json:"alert_rule_id"`
	Payload        []byte    `json:"payload"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent, arg.OrganizationID, arg.AlertRuleID, arg.Payload)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AlertRuleID,
		&i.TriggeredAt,
		&i.Payload,
	)
	return i, err
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, organization_id, alert_rule_id, triggered_at, payload FROM alert_events WHERE organization_id = $1 ORDER BY triggered_at DESC LIMIT $2
`

type ListAlertEventsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AlertRuleID,
			&i.TriggeredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled, last_triggered_at, created_at, updated_at FROM alert_rules WHERE organization_id = $1 ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListAlertRules(ctx context.Context, organizationID uuid.UUID) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AlertType,
			&i.Threshold,
			&i.WindowMinutes,
			&i.CooldownMinutes,
			&i.NotifyRoles,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonFreeOrgIDs = `-- name: ListNonFreeOrgIDs :many
SELECT DISTINCT ar.organization_id FROM alert_rules ar
JOIN organizations o ON o.id = ar.organization_id
WHERE ar.enabled = TRUE AND o.plan != 'free'
`

func (q *Queries) ListNonFreeOrgIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listNonFreeOrgIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var organization_id uuid.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryTriggerAlert = `-- name: TryTriggerAlert :one
UPDATE alert_rules
SET last_triggered_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND enabled = TRUE
  AND (last_triggered_at IS NULL
       OR last_triggered_at < NOW() - (cooldown_minutes * interval '1 minute'))
RETURNING id
`

func (q *Queries) TryTriggerAlert(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tryTriggerAlert, id)
	err := row.Scan(&id)
	return id, err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $3, threshold = $4, window_minutes = $5, cooldown_minutes = $6, notify_roles = $7, enabled = $8, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, alert_type, threshold, window_minutes, cooldown_minutes, notify_roles, enabled, last_triggered_at, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	ID              uuid.UUID      `json:"id"`
	OrganizationID  uuid.UUID      `json:"organization_id"`
	Name            string         `json:"name"`
	Threshold       pgtype.Numeric `json:"threshold"`
	WindowMinutes   int32          `json:"window_minutes"`
	CooldownMinutes int32          `json:"cooldown_minutes"`
	NotifyRoles     []string       `json:"notify_roles"`
	Enabled         bool           `json:"enabled"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Threshold,
		arg.WindowMinutes,
		arg.CooldownMinutes,
		arg.NotifyRoles,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AlertType,
		&i.Threshold,
		&i.WindowMinutes,
		&i.CooldownMinutes,
		&i.NotifyRoles,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
