// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (organization_id, name, provider_type, provider_key_encrypted, base_url, key_digest, display)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, provider_type, provider_key_encrypted, base_url, key_digest, display, active, last_used_at, created_at, deactivated_by_deletion
`

type CreateApiKeyParams struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	Name                 string    `json:"name"`
	ProviderType         string    `json:"provider_type"`
	ProviderKeyEncrypted []byte    `json:"provider_key_encrypted"`
	BaseUrl              *string   `json:"base_url"`
	KeyDigest            string    `json:"key_digest"`
	Display              string    `json:"display"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.OrganizationID,
		arg.Name,
		arg.ProviderType,
		arg.ProviderKeyEncrypted,
		arg.BaseUrl,
		arg.KeyDigest,
		arg.Display,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProviderType,
		&i.ProviderKeyEncrypted,
		&i.BaseUrl,
		&i.KeyDigest,
		&i.Display,
		&i.Active,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeactivatedByDeletion,
	)
	return i, err
}

const deactivateApiKey = `-- name: DeactivateApiKey :exec
UPDATE api_keys
SET active = FALSE
WHERE id = $1 AND organization_id = $2
`

type DeactivateApiKeyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeactivateApiKey(ctx context.Context, arg DeactivateApiKeyParams) error {
	_, err := q.db.Exec(ctx, deactivateApiKey, arg.ID, arg.OrganizationID)
	return err
}

const deactivateApiKeysByOrg = `-- name: DeactivateApiKeysByOrg :exec
UPDATE api_keys
SET active = FALSE, deactivated_by_deletion = TRUE
WHERE organization_id = $1 AND active = TRUE
`

func (q *Queries) DeactivateApiKeysByOrg(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateApiKeysByOrg, organizationID)
	return err
}

const getApiKeyByDigest = `-- name: GetApiKeyByDigest :one
SELECT id, organization_id, name, provider_type, provider_key_encrypted, base_url, key_digest, display, active, last_used_at, created_at, deactivated_by_deletion FROM api_keys
WHERE key_digest = $1 AND active = TRUE
LIMIT 1
`

func (q *Queries) GetApiKeyByDigest(ctx context.Context, keyDigest string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByDigest, keyDigest)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProviderType,
		&i.ProviderKeyEncrypted,
		&i.BaseUrl,
		&i.KeyDigest,
		&i.Display,
		&i.Active,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeactivatedByDeletion,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, organization_id, name, provider_type, provider_key_encrypted, base_url, key_digest, display, active, last_used_at, created_at, deactivated_by_deletion FROM api_keys
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type GetApiKeyByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetApiKeyByID(ctx context.Context, arg GetApiKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProviderType,
		&i.ProviderKeyEncrypted,
		&i.BaseUrl,
		&i.KeyDigest,
		&i.Display,
		&i.Active,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeactivatedByDeletion,
	)
	return i, err
}

const listApiKeysByOrg = `-- name: ListApiKeysByOrg :many
SELECT id, organization_id, name, provider_type, base_url, display, active, last_used_at, created_at FROM api_keys
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT 200
`

type ListApiKeysByOrgRow struct {
	ID             uuid.UUID    `json:"id"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	Name           string       `json:"name"`
	ProviderType   string       `json:"provider_type"`
	BaseUrl        *string      `json:"base_url"`
	Display        string       `json:"display"`
	Active         bool         `json:"active"`
	LastUsedAt     sql.NullTime `json:"last_used_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

func (q *Queries) ListApiKeysByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListApiKeysByOrgRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysByOrgRow{}
	for rows.Next() {
		var i ListApiKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ProviderType,
			&i.BaseUrl,
			&i.Display,
			&i.Active,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateApiKeysByOrg = `-- name: ReactivateApiKeysByOrg :exec
UPDATE api_keys
SET active = TRUE, deactivated_by_deletion = FALSE
WHERE organization_id = $1 AND deactivated_by_deletion = TRUE
`

func (q *Queries) ReactivateApiKeysByOrg(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateApiKeysByOrg, organizationID)
	return err
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
