// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failure_clusters.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFailureCluster = `-- name: CreateFailureCluster :one
INSERT INTO failure_clusters (organization_id, label)
VALUES ($1, $2)
RETURNING id, organization_id, label, description, session_count, created_at, updated_at
`

type CreateFailureClusterParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) CreateFailureCluster(ctx context.Context, arg CreateFailureClusterParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, createFailureCluster, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateFailureClusterByLabel = `-- name: FindOrCreateFailureClusterByLabel :one
INSERT INTO failure_clusters (organization_id, label)
VALUES ($1, $2)
ON CONFLICT (organization_id, label) DO UPDATE SET updated_at = NOW()
RETURNING id, organization_id, label, description, session_count, created_at, updated_at
`

type FindOrCreateFailureClusterByLabelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) FindOrCreateFailureClusterByLabel(ctx context.Context, arg FindOrCreateFailureClusterByLabelParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, findOrCreateFailureClusterByLabel, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailureClusterByID = `-- name: GetFailureClusterByID :one
SELECT id, organization_id, label, description, session_count, created_at, updated_at FROM failure_clusters
WHERE id = $1 AND organization_id = $2
`

type GetFailureClusterByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetFailureClusterByID(ctx context.Context, arg GetFailureClusterByIDParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, getFailureClusterByID, arg.ID, arg.OrganizationID)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailureClusterByLabel = `-- name: GetFailureClusterByLabel :one
SELECT id, organization_id, label, description, session_count, created_at, updated_at FROM failure_clusters
WHERE organization_id = $1 AND label = $2
`

type GetFailureClusterByLabelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) GetFailureClusterByLabel(ctx context.Context, arg GetFailureClusterByLabelParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, getFailureClusterByLabel, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByIDForIntel = `-- name: GetOrganizationByIDForIntel :one
SELECT id, plan, locale FROM organizations WHERE id = $1
`

type GetOrganizationByIDForIntelRow struct {
	ID     uuid.UUID `json:"id"`
	Plan   string    `json:"plan"`
	Locale string    `json:"locale"`
}

func (q *Queries) GetOrganizationByIDForIntel(ctx context.Context, id uuid.UUID) (GetOrganizationByIDForIntelRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByIDForIntel, id)
	var i GetOrganizationByIDForIntelRow
	err := row.Scan(&i.ID, &i.Plan, &i.Locale)
	return i, err
}

const incrementFailureClusterCount = `-- name: IncrementFailureClusterCount :exec
UPDATE failure_clusters
SET session_count = session_count + 1, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
`

type IncrementFailureClusterCountParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) IncrementFailureClusterCount(ctx context.Context, arg IncrementFailureClusterCountParams) error {
	_, err := q.db.Exec(ctx, incrementFailureClusterCount, arg.ID, arg.OrganizationID)
	return err
}

const insertSessionFailureCluster = `-- name: InsertSessionFailureCluster :exec
INSERT INTO session_failure_clusters (session_id, failure_cluster_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSessionFailureClusterParams struct {
	SessionID        uuid.UUID `json:"session_id"`
	FailureClusterID uuid.UUID `json:"failure_cluster_id"`
}

func (q *Queries) InsertSessionFailureCluster(ctx context.Context, arg InsertSessionFailureClusterParams) error {
	_, err := q.db.Exec(ctx, insertSessionFailureCluster, arg.SessionID, arg.FailureClusterID)
	return err
}

const listFailureClusterLabels = `-- name: ListFailureClusterLabels :many
SELECT id, label FROM failure_clusters
WHERE organization_id = $1
ORDER BY session_count DESC
LIMIT 50
`

type ListFailureClusterLabelsRow struct {
	ID    uuid.UUID `json:"id"`
	Label string    `json:"label"`
}

func (q *Queries) ListFailureClusterLabels(ctx context.Context, organizationID uuid.UUID) ([]ListFailureClusterLabelsRow, error) {
	rows, err := q.db.Query(ctx, listFailureClusterLabels, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailureClusterLabelsRow{}
	for rows.Next() {
		var i ListFailureClusterLabelsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailureClusters = `-- name: ListFailureClusters :many
SELECT id, label, session_count, created_at, updated_at
FROM failure_clusters
WHERE organization_id = $1
ORDER BY session_count DESC
`

type ListFailureClustersRow struct {
	ID           uuid.UUID `json:"id"`
	Label        string    `json:"label"`
	SessionCount int32     `json:"session_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListFailureClusters(ctx context.Context, organizationID uuid.UUID) ([]ListFailureClustersRow, error) {
	rows, err := q.db.Query(ctx, listFailureClusters, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailureClustersRow{}
	for rows.Next() {
		var i ListFailureClustersRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.SessionCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByCluster = `-- name: ListSessionsByCluster :many
SELECT s.id, s.api_key_id, s.status, s.span_count,
       s.started_at, s.last_span_at, s.closed_at,
       k.name AS api_key_name,
       s.agent_name
FROM session_failure_clusters sfc
JOIN sessions s ON s.id = sfc.session_id
JOIN api_keys k ON k.id = s.api_key_id
WHERE sfc.failure_cluster_id = $1 AND s.organization_id = $2
ORDER BY s.started_at DESC
LIMIT 100
`

type ListSessionsByClusterParams struct {
	FailureClusterID uuid.UUID `json:"failure_cluster_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
}

type ListSessionsByClusterRow struct {
	ID         uuid.UUID    `json:"id"`
	ApiKeyID   uuid.UUID    `json:"api_key_id"`
	Status     string       `json:"status"`
	SpanCount  int32        `json:"span_count"`
	StartedAt  time.Time    `json:"started_at"`
	LastSpanAt time.Time    `json:"last_span_at"`
	ClosedAt   sql.NullTime `json:"closed_at"`
	ApiKeyName string       `json:"api_key_name"`
	AgentName  *string      `json:"agent_name"`
}

func (q *Queries) ListSessionsByCluster(ctx context.Context, arg ListSessionsByClusterParams) ([]ListSessionsByClusterRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByCluster, arg.FailureClusterID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByClusterRow{}
	for rows.Next() {
		var i ListSessionsByClusterRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Status,
			&i.SpanCount,
			&i.StartedAt,
			&i.LastSpanAt,
			&i.ClosedAt,
			&i.ApiKeyName,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionNarrative = `-- name: UpdateSessionNarrative :exec
UPDATE sessions SET narrative = $2, updated_at = NOW() WHERE id = $1 AND organization_id = $3
`

type UpdateSessionNarrativeParams struct {
	ID             uuid.UUID `json:"id"`
	Narrative      *string   `json:"narrative"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateSessionNarrative(ctx context.Context, arg UpdateSessionNarrativeParams) error {
	_, err := q.db.Exec(ctx, updateSessionNarrative, arg.ID, arg.Narrative, arg.OrganizationID)
	return err
}
