// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failure_clusters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFailureCluster = `-- name: CreateFailureCluster :one
INSERT INTO failure_clusters (organization_id, label)
VALUES ($1, $2)
RETURNING id, organization_id, label, description, session_count, created_at, updated_at
`

type CreateFailureClusterParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) CreateFailureCluster(ctx context.Context, arg CreateFailureClusterParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, createFailureCluster, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateFailureClusterByLabel = `-- name: FindOrCreateFailureClusterByLabel :one
INSERT INTO failure_clusters (organization_id, label)
VALUES ($1, $2)
ON CONFLICT (organization_id, label) DO UPDATE SET updated_at = NOW()
RETURNING id, organization_id, label, description, session_count, created_at, updated_at
`

type FindOrCreateFailureClusterByLabelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) FindOrCreateFailureClusterByLabel(ctx context.Context, arg FindOrCreateFailureClusterByLabelParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, findOrCreateFailureClusterByLabel, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailureClusterByID = `-- name: GetFailureClusterByID :one
SELECT id, organization_id, label, description, session_count, created_at, updated_at FROM failure_clusters
WHERE id = $1 AND organization_id = $2
`

type GetFailureClusterByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetFailureClusterByID(ctx context.Context, arg GetFailureClusterByIDParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, getFailureClusterByID, arg.ID, arg.OrganizationID)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailureClusterByLabel = `-- name: GetFailureClusterByLabel :one
SELECT id, organization_id, label, description, session_count, created_at, updated_at FROM failure_clusters
WHERE organization_id = $1 AND label = $2
`

type GetFailureClusterByLabelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) GetFailureClusterByLabel(ctx context.Context, arg GetFailureClusterByLabelParams) (FailureCluster, error) {
	row := q.db.QueryRow(ctx, getFailureClusterByLabel, arg.OrganizationID, arg.Label)
	var i FailureCluster
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Label,
		&i.Description,
		&i.SessionCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByIDForIntel = `-- name: GetOrganizationByIDForIntel :one
SELECT id, plan, locale FROM organizations WHERE id = $1
`

type GetOrganizationByIDForIntelRow struct {
	ID     uuid.UUID `json:"id"`
	Plan   string    `json:"plan"`
	Locale string    `json:"locale"`
}

func (q *Queries) GetOrganizationByIDForIntel(ctx context.Context, id uuid.UUID) (GetOrganizationByIDForIntelRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByIDForIntel, id)
	var i GetOrganizationByIDForIntelRow
	err := row.Scan(&i.ID, &i.Plan, &i.Locale)
	return i, err
}

const incrementFailureClusterCount = `-- name: IncrementFailureClusterCount :exec
UPDATE failure_clusters
SET session_count = session_count + 1, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
`

type IncrementFailureClusterCountParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) IncrementFailureClusterCount(ctx context.Context, arg IncrementFailureClusterCountParams) error {
	_, err := q.db.Exec(ctx, incrementFailureClusterCount, arg.ID, arg.OrganizationID)
	return err
}

const insertSessionFailureCluster = `-- name: InsertSessionFailureCluster :exec
INSERT INTO session_failure_clusters (session_id, failure_cluster_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSessionFailureClusterParams struct {
	SessionID        uuid.UUID `json:"session_id"`
	FailureClusterID uuid.UUID `json:"failure_cluster_id"`
}

func (q *Queries) InsertSessionFailureCluster(ctx context.Context, arg InsertSessionFailureClusterParams) error {
	_, err := q.db.Exec(ctx, insertSessionFailureCluster, arg.SessionID, arg.FailureClusterID)
	return err
}

const listFailureClusterLabels = `-- name: ListFailureClusterLabels :many
SELECT id, label FROM failure_clusters
WHERE organization_id = $1
ORDER BY session_count DESC
LIMIT 50
`

type ListFailureClusterLabelsRow struct {
	ID    uuid.UUID `json:"id"`
	Label string    `json:"label"`
}

func (q *Queries) ListFailureClusterLabels(ctx context.Context, organizationID uuid.UUID) ([]ListFailureClusterLabelsRow, error) {
	rows, err := q.db.Query(ctx, listFailureClusterLabels, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailureClusterLabelsRow{}
	for rows.Next() {
		var i ListFailureClusterLabelsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedFailureClusters = `-- name: SeedFailureClusters :exec
INSERT INTO failure_clusters (organization_id, label)
VALUES ($1, $2)
ON CONFLICT (organization_id, label) DO NOTHING
`

type SeedFailureClustersParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
}

func (q *Queries) SeedFailureClusters(ctx context.Context, arg SeedFailureClustersParams) error {
	_, err := q.db.Exec(ctx, seedFailureClusters, arg.OrganizationID, arg.Label)
	return err
}

const updateSessionNarrative = `-- name: UpdateSessionNarrative :exec
UPDATE sessions SET narrative = $2, updated_at = NOW() WHERE id = $1 AND organization_id = $3
`

type UpdateSessionNarrativeParams struct {
	ID             uuid.UUID `json:"id"`
	Narrative      *string   `json:"narrative"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateSessionNarrative(ctx context.Context, arg UpdateSessionNarrativeParams) error {
	_, err := q.db.Exec(ctx, updateSessionNarrative, arg.ID, arg.Narrative, arg.OrganizationID)
	return err
}
