// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE invites
SET accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvite, id)
	return err
}

const countPendingInvitesByOrg = `-- name: CountPendingInvitesByOrg :one
SELECT COUNT(*) FROM invites
WHERE organization_id = $1 AND accepted_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountPendingInvitesByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitesByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (organization_id, invited_by, email, token_hash, role, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, invited_by, email, token_hash, role, accepted_at, expires_at, created_at
`

type CreateInviteParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	InvitedBy      uuid.UUID `json:"invited_by"`
	Email          *string   `json:"email"`
	TokenHash      string    `json:"token_hash"`
	Role           string    `json:"role"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrganizationID,
		arg.InvitedBy,
		arg.Email,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
DELETE FROM invites
WHERE expires_at < NOW() AND accepted_at IS NULL
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvites)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites
WHERE id = $1 AND organization_id = $2
`

type DeleteInviteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.OrganizationID)
	return err
}

const getInviteByEmailAndOrg = `-- name: GetInviteByEmailAndOrg :one
SELECT id, organization_id, invited_by, email, token_hash, role, accepted_at, expires_at, created_at FROM invites
WHERE email = $1 AND organization_id = $2 AND accepted_at IS NULL AND expires_at > NOW()
LIMIT 1
`

type GetInviteByEmailAndOrgParams struct {
	Email          *string   `json:"email"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetInviteByEmailAndOrg(ctx context.Context, arg GetInviteByEmailAndOrgParams) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByEmailAndOrg, arg.Email, arg.OrganizationID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, organization_id, invited_by, email, token_hash, role, accepted_at, expires_at, created_at FROM invites
WHERE token_hash = $1 AND accepted_at IS NULL AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitesByOrg = `-- name: ListPendingInvitesByOrg :many
SELECT id, organization_id, invited_by, email, token_hash, role, accepted_at, expires_at, created_at FROM invites
WHERE organization_id = $1 AND accepted_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitesByOrg(ctx context.Context, organizationID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitedBy,
			&i.Email,
			&i.TokenHash,
			&i.Role,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
