// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: masking_maps.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSpanMaskingMaps = `-- name: GetSpanMaskingMaps :many
SELECT id, span_id, mask_type, original_value, masked_value, created_at
FROM span_masking_maps
WHERE span_id = $1
ORDER BY created_at
`

func (q *Queries) GetSpanMaskingMaps(ctx context.Context, spanID uuid.UUID) ([]SpanMaskingMap, error) {
	rows, err := q.db.Query(ctx, getSpanMaskingMaps, spanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpanMaskingMap{}
	for rows.Next() {
		var i SpanMaskingMap
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.MaskType,
			&i.OriginalValue,
			&i.MaskedValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSpanMaskingMap = `-- name: InsertSpanMaskingMap :exec
INSERT INTO span_masking_maps (span_id, mask_type, original_value, masked_value)
VALUES ($1, $2, $3, $4)
`

type InsertSpanMaskingMapParams struct {
	SpanID        uuid.UUID `json:"span_id"`
	MaskType      string    `json:"mask_type"`
	OriginalValue string    `json:"original_value"`
	MaskedValue   string    `json:"masked_value"`
}

func (q *Queries) InsertSpanMaskingMap(ctx context.Context, arg InsertSpanMaskingMapParams) error {
	_, err := q.db.Exec(ctx, insertSpanMaskingMap,
		arg.SpanID,
		arg.MaskType,
		arg.OriginalValue,
		arg.MaskedValue,
	)
	return err
}
