// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembershipsByOrg = `-- name: CountMembershipsByOrg :one
SELECT COUNT(*) FROM memberships
WHERE organization_id = $1
`

func (q *Queries) CountMembershipsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE id = $1 AND organization_id = $2
`

type DeleteMembershipParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.ID, arg.OrganizationID)
	return err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, u.email, u.name as user_name FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.id = $1 AND m.organization_id = $2
LIMIT 1
`

type GetMembershipByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetMembershipByIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
	Email          string    `json:"email"`
	UserName       string    `json:"user_name"`
}

func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (GetMembershipByIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.ID, arg.OrganizationID)
	var i GetMembershipByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.UserName,
	)
	return i, err
}

const getMembershipByOrgAndUser = `-- name: GetMembershipByOrgAndUser :one
SELECT id, organization_id, user_id, role, created_at FROM memberships
WHERE organization_id = $1 AND user_id = $2
LIMIT 1
`

type GetMembershipByOrgAndUserParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipByOrgAndUser(ctx context.Context, arg GetMembershipByOrgAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerMembership = `-- name: GetOwnerMembership :one
SELECT id, organization_id, user_id, role, created_at FROM memberships
WHERE organization_id = $1 AND role = 'owner'
LIMIT 1
`

func (q *Queries) GetOwnerMembership(ctx context.Context, organizationID uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getOwnerMembership, organizationID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, u.email, u.name as user_name FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.created_at ASC
LIMIT 200
`

type ListMembershipsByOrgRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
	Email          string    `json:"email"`
	UserName       string    `json:"user_name"`
}

func (q *Queries) ListMembershipsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListMembershipsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByOrgRow{}
	for rows.Next() {
		var i ListMembershipsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT organization_id FROM memberships
WHERE user_id = $1
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var organization_id uuid.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships
SET role = $1
WHERE id = $2 AND organization_id = $3
`

type UpdateMembershipRoleParams struct {
	Role           string    `json:"role"`
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.Role, arg.ID, arg.OrganizationID)
	return err
}
