// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertEvent struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	AlertRuleID    uuid.UUID `json:"alert_rule_id"`
	TriggeredAt    time.Time `json:"triggered_at"`
	Payload        []byte    `json:"payload"`
}

type AlertRule struct {
	ID              uuid.UUID      `json:"id"`
	OrganizationID  uuid.UUID      `json:"organization_id"`
	Name            string         `json:"name"`
	AlertType       string         `json:"alert_type"`
	Threshold       pgtype.Numeric `json:"threshold"`
	WindowMinutes   int32          `json:"window_minutes"`
	CooldownMinutes int32          `json:"cooldown_minutes"`
	NotifyRoles     []string       `json:"notify_roles"`
	Enabled         bool           `json:"enabled"`
	LastTriggeredAt sql.NullTime   `json:"last_triggered_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type ApiKey struct {
	ID                    uuid.UUID    `json:"id"`
	OrganizationID        uuid.UUID    `json:"organization_id"`
	Name                  string       `json:"name"`
	ProviderType          string       `json:"provider_type"`
	ProviderKeyEncrypted  []byte       `json:"provider_key_encrypted"`
	BaseUrl               *string      `json:"base_url"`
	KeyDigest             string       `json:"key_digest"`
	Display               string       `json:"display"`
	Active                bool         `json:"active"`
	LastUsedAt            sql.NullTime `json:"last_used_at"`
	CreatedAt             time.Time    `json:"created_at"`
	DeactivatedByDeletion bool         `json:"deactivated_by_deletion"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type FailureCluster struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          string    `json:"label"`
	Description    *string   `json:"description"`
	SessionCount   int32     `json:"session_count"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Invite struct {
	ID             uuid.UUID    `json:"id"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	InvitedBy      uuid.UUID    `json:"invited_by"`
	Email          *string      `json:"email"`
	TokenHash      string       `json:"token_hash"`
	Role           string       `json:"role"`
	AcceptedAt     sql.NullTime `json:"accepted_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type Membership struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}

type ModelPrice struct {
	ID                  uuid.UUID      `json:"id"`
	ProviderType        string         `json:"provider_type"`
	Model               string         `json:"model"`
	InputPricePerToken  pgtype.Numeric `json:"input_price_per_token"`
	OutputPricePerToken pgtype.Numeric `json:"output_price_per_token"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Organization struct {
	ID                    uuid.UUID    `json:"id"`
	Name                  string       `json:"name"`
	Slug                  string       `json:"slug"`
	Plan                  string       `json:"plan"`
	Status                string       `json:"status"`
	DeletionScheduledAt   sql.NullTime `json:"deletion_scheduled_at"`
	Locale                string       `json:"locale"`
	SessionTimeoutSeconds int32        `json:"session_timeout_seconds"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	StoreSpanContent      bool         `json:"store_span_content"`
	MaskingConfig         []byte       `json:"masking_config"`
}

type PasswordResetToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type ProRequest struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Company   string    `json:"company"`
	Message   string    `json:"message"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	ApiKeyID       uuid.UUID      `json:"api_key_id"`
	ExternalID     *string        `json:"external_id"`
	AgentName      *string        `json:"agent_name"`
	Status         string         `json:"status"`
	Narrative      *string        `json:"narrative"`
	TotalCostUsd   pgtype.Numeric `json:"total_cost_usd"`
	SpanCount      int32          `json:"span_count"`
	StartedAt      time.Time      `json:"started_at"`
	LastSpanAt     time.Time      `json:"last_span_at"`
	ClosedAt       sql.NullTime   `json:"closed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type SessionFailureCluster struct {
	SessionID        uuid.UUID `json:"session_id"`
	FailureClusterID uuid.UUID `json:"failure_cluster_id"`
}

type Span struct {
	ID                 uuid.UUID      `json:"id"`
	SessionID          uuid.UUID      `json:"session_id"`
	OrganizationID     uuid.UUID      `json:"organization_id"`
	ProviderType       string         `json:"provider_type"`
	Model              string         `json:"model"`
	Input              *string        `json:"input"`
	Output             *string        `json:"output"`
	InputTokens        *int32         `json:"input_tokens"`
	OutputTokens       *int32         `json:"output_tokens"`
	CostUsd            pgtype.Numeric `json:"cost_usd"`
	DurationMs         int32          `json:"duration_ms"`
	HttpStatus         int32          `json:"http_status"`
	StartedAt          time.Time      `json:"started_at"`
	CreatedAt          time.Time      `json:"created_at"`
	FinishReason       string         `json:"finish_reason"`
	MaskingApplied     bool           `json:"masking_applied"`
	AnomalyReason      *string        `json:"anomaly_reason"`
	AnomalyCategory    *string        `json:"anomaly_category"`
	ClientDisconnected bool           `json:"client_disconnected"`
}

type SpanMaskingMap struct {
	ID            uuid.UUID `json:"id"`
	SpanID        uuid.UUID `json:"span_id"`
	MaskType      string    `json:"mask_type"`
	OriginalValue string    `json:"original_value"`
	MaskedValue   string    `json:"masked_value"`
	CreatedAt     time.Time `json:"created_at"`
}

type SpanSystemPrompt struct {
	SpanID         uuid.UUID `json:"span_id"`
	SystemPromptID uuid.UUID `json:"system_prompt_id"`
}

type SystemPrompt struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Content        string    `json:"content"`
	ContentHash    string    `json:"content_hash"`
	ShortUid       string    `json:"short_uid"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID    `json:"id"`
	Email             string       `json:"email"`
	Name              string       `json:"name"`
	PasswordHash      string       `json:"password_hash"`
	EmailVerifiedAt   sql.NullTime `json:"email_verified_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	PasswordChangedAt sql.NullTime `json:"password_changed_at"`
	AcceptedTermsAt   sql.NullTime `json:"accepted_terms_at"`
	AcceptedPrivacyAt sql.NullTime `json:"accepted_privacy_at"`
	PolicyVersion     int32        `json:"policy_version"`
}
