// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, plan)
VALUES ($1, $2, $3)
RETURNING id, name, slug, plan, status, deletion_scheduled_at, locale, session_timeout_seconds, created_at, updated_at, store_span_content, masking_config
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	Plan string `json:"plan"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.Plan)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.DeletionScheduledAt,
		&i.Locale,
		&i.SessionTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreSpanContent,
		&i.MaskingConfig,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organization_id, user_id, role, created_at FROM memberships
WHERE organization_id = $1 AND user_id = $2
LIMIT 1
`

type GetMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, plan, status, deletion_scheduled_at, locale, session_timeout_seconds, created_at, updated_at, store_span_content, masking_config FROM organizations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.DeletionScheduledAt,
		&i.Locale,
		&i.SessionTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreSpanContent,
		&i.MaskingConfig,
	)
	return i, err
}

const getOrganizationByIDForUpdate = `-- name: GetOrganizationByIDForUpdate :one
SELECT id, name, slug, plan, status, deletion_scheduled_at, locale, session_timeout_seconds, created_at, updated_at, store_span_content, masking_config FROM organizations
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetOrganizationByIDForUpdate(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByIDForUpdate, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.DeletionScheduledAt,
		&i.Locale,
		&i.SessionTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreSpanContent,
		&i.MaskingConfig,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, plan, status, deletion_scheduled_at, locale, session_timeout_seconds, created_at, updated_at, store_span_content, masking_config FROM organizations
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.DeletionScheduledAt,
		&i.Locale,
		&i.SessionTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreSpanContent,
		&i.MaskingConfig,
	)
	return i, err
}

const getOrganizationPrivacySettings = `-- name: GetOrganizationPrivacySettings :one
SELECT store_span_content, masking_config FROM organizations
WHERE id = $1
`

type GetOrganizationPrivacySettingsRow struct {
	StoreSpanContent bool   `json:"store_span_content"`
	MaskingConfig    []byte `json:"masking_config"`
}

func (q *Queries) GetOrganizationPrivacySettings(ctx context.Context, id uuid.UUID) (GetOrganizationPrivacySettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationPrivacySettings, id)
	var i GetOrganizationPrivacySettingsRow
	err := row.Scan(&i.StoreSpanContent, &i.MaskingConfig)
	return i, err
}

const getOrganizationsByUserID = `-- name: GetOrganizationsByUserID :many
SELECT o.id, o.name, o.slug, o.plan, o.status, o.deletion_scheduled_at, o.locale, o.session_timeout_seconds, o.created_at, o.updated_at, o.store_span_content, o.masking_config FROM organizations o
JOIN memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at ASC
`

func (q *Queries) GetOrganizationsByUserID(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Status,
			&i.DeletionScheduledAt,
			&i.Locale,
			&i.SessionTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreSpanContent,
			&i.MaskingConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationsDueForDeletion = `-- name: GetOrganizationsDueForDeletion :many
SELECT id, name, slug, plan, status, deletion_scheduled_at, locale, session_timeout_seconds, created_at, updated_at, store_span_content, masking_config FROM organizations
WHERE status = 'pending_deletion' AND deletion_scheduled_at <= NOW()
`

func (q *Queries) GetOrganizationsDueForDeletion(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsDueForDeletion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Status,
			&i.DeletionScheduledAt,
			&i.Locale,
			&i.SessionTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreSpanContent,
			&i.MaskingConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreOrganization = `-- name: RestoreOrganization :exec
UPDATE organizations
SET status = 'active', deletion_scheduled_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreOrganization, id)
	return err
}

const setOrganizationPendingDeletion = `-- name: SetOrganizationPendingDeletion :exec
UPDATE organizations
SET status = 'pending_deletion', deletion_scheduled_at = $2, updated_at = NOW()
WHERE id = $1
`

type SetOrganizationPendingDeletionParams struct {
	ID                  uuid.UUID    `json:"id"`
	DeletionScheduledAt sql.NullTime `json:"deletion_scheduled_at"`
}

func (q *Queries) SetOrganizationPendingDeletion(ctx context.Context, arg SetOrganizationPendingDeletionParams) error {
	_, err := q.db.Exec(ctx, setOrganizationPendingDeletion, arg.ID, arg.DeletionScheduledAt)
	return err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :exec
UPDATE organizations
SET name = $1, slug = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateOrganizationNameParams struct {
	Name string    `json:"name"`
	Slug string    `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationName, arg.Name, arg.Slug, arg.ID)
	return err
}

const updateOrganizationPrivacySettings = `-- name: UpdateOrganizationPrivacySettings :exec
UPDATE organizations
SET store_span_content = $2, masking_config = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationPrivacySettingsParams struct {
	ID               uuid.UUID `json:"id"`
	StoreSpanContent bool      `json:"store_span_content"`
	MaskingConfig    []byte    `json:"masking_config"`
}

func (q *Queries) UpdateOrganizationPrivacySettings(ctx context.Context, arg UpdateOrganizationPrivacySettingsParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationPrivacySettings, arg.ID, arg.StoreSpanContent, arg.MaskingConfig)
	return err
}

const updateOrganizationSettings = `-- name: UpdateOrganizationSettings :exec
UPDATE organizations
SET locale = $2, session_timeout_seconds = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationSettingsParams struct {
	ID                    uuid.UUID `json:"id"`
	Locale                string    `json:"locale"`
	SessionTimeoutSeconds int32     `json:"session_timeout_seconds"`
}

func (q *Queries) UpdateOrganizationSettings(ctx context.Context, arg UpdateOrganizationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationSettings, arg.ID, arg.Locale, arg.SessionTimeoutSeconds)
	return err
}
