// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pro_requests.sql

package db

import (
	"context"
)

const createProRequest = `-- name: CreateProRequest :one
INSERT INTO pro_requests (email, company, message, source)
VALUES ($1, $2, $3, $4)
RETURNING id, email, company, message, source, created_at
`

type CreateProRequestParams struct {
	Email   string `json:"email"`
	Company string `json:"company"`
	Message string `json:"message"`
	Source  string `json:"source"`
}

func (q *Queries) CreateProRequest(ctx context.Context, arg CreateProRequestParams) (ProRequest, error) {
	row := q.db.QueryRow(ctx, createProRequest,
		arg.Email,
		arg.Company,
		arg.Message,
		arg.Source,
	)
	var i ProRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Company,
		&i.Message,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
