// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeSessionsWithStatus = `-- name: CloseSessionsWithStatus :exec
UPDATE sessions
SET status = $1,
    closed_at = NOW(),
    updated_at = NOW()
WHERE id = ANY($2::uuid[])
  AND status = 'in_progress'
`

type CloseSessionsWithStatusParams struct {
	Status     string      `json:"status"`
	SessionIds []uuid.UUID `json:"session_ids"`
}

func (q *Queries) CloseSessionsWithStatus(ctx context.Context, arg CloseSessionsWithStatusParams) error {
	_, err := q.db.Exec(ctx, closeSessionsWithStatus, arg.Status, arg.SessionIds)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (organization_id, api_key_id, external_id, agent_name, status)
VALUES ($1, $2, $3, $4, 'in_progress')
RETURNING id
`

type CreateSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	ExternalID     *string   `json:"external_id"`
	AgentName      *string   `json:"agent_name"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.OrganizationID,
		arg.ApiKeyID,
		arg.ExternalID,
		arg.AgentName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findActiveExplicitSession = `-- name: FindActiveExplicitSession :one
SELECT id FROM sessions
WHERE api_key_id = $1 AND external_id = $2 AND status = 'in_progress'
LIMIT 1
`

type FindActiveExplicitSessionParams struct {
	ApiKeyID   uuid.UUID `json:"api_key_id"`
	ExternalID *string   `json:"external_id"`
}

func (q *Queries) FindActiveExplicitSession(ctx context.Context, arg FindActiveExplicitSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveExplicitSession, arg.ApiKeyID, arg.ExternalID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findActiveSessionForAPIKey = `-- name: FindActiveSessionForAPIKey :one
SELECT id FROM sessions
WHERE api_key_id = $1
  AND status = 'in_progress'
  AND last_span_at >= NOW() - ($2::int * interval '1 second')
ORDER BY last_span_at DESC
LIMIT 1
`

type FindActiveSessionForAPIKeyParams struct {
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
}

func (q *Queries) FindActiveSessionForAPIKey(ctx context.Context, arg FindActiveSessionForAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveSessionForAPIKey, arg.ApiKeyID, arg.TimeoutSeconds)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findOrCreateExplicitSession = `-- name: FindOrCreateExplicitSession :one
INSERT INTO sessions (organization_id, api_key_id, external_id, agent_name, status)
VALUES ($1, $2, $3, $4, 'in_progress')
ON CONFLICT (api_key_id, external_id) WHERE status = 'in_progress' AND external_id IS NOT NULL
DO UPDATE SET updated_at = NOW()
RETURNING id
`

type FindOrCreateExplicitSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	ExternalID     *string   `json:"external_id"`
	AgentName      *string   `json:"agent_name"`
}

func (q *Queries) FindOrCreateExplicitSession(ctx context.Context, arg FindOrCreateExplicitSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findOrCreateExplicitSession,
		arg.OrganizationID,
		arg.ApiKeyID,
		arg.ExternalID,
		arg.AgentName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getIdleSessionsForClosure = `-- name: GetIdleSessionsForClosure :many
SELECT s.id, s.organization_id, s.span_count
FROM sessions s
JOIN organizations o ON o.id = s.organization_id
WHERE s.status = 'in_progress'
  AND s.last_span_at < NOW() - (o.session_timeout_seconds * interval '1 second')
LIMIT 200
`

type GetIdleSessionsForClosureRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SpanCount      int32     `json:"span_count"`
}

func (q *Queries) GetIdleSessionsForClosure(ctx context.Context) ([]GetIdleSessionsForClosureRow, error) {
	rows, err := q.db.Query(ctx, getIdleSessionsForClosure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIdleSessionsForClosureRow{}
	for rows.Next() {
		var i GetIdleSessionsForClosureRow
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.SpanCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT s.id, s.organization_id, s.api_key_id, s.external_id, s.agent_name,
       s.status, s.narrative, s.total_cost_usd, s.span_count,
       s.started_at, s.last_span_at, s.closed_at, s.created_at, s.updated_at,
       k.name AS api_key_name
FROM sessions s
JOIN api_keys k ON k.id = s.api_key_id
WHERE s.id = $1 AND s.organization_id = $2
`

type GetSessionByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetSessionByIDRow struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	ApiKeyID       uuid.UUID      `json:"api_key_id"`
	ExternalID     *string        `json:"external_id"`
	AgentName      *string        `json:"agent_name"`
	Status         string         `json:"status"`
	Narrative      *string        `json:"narrative"`
	TotalCostUsd   pgtype.Numeric `json:"total_cost_usd"`
	SpanCount      int32          `json:"span_count"`
	StartedAt      time.Time      `json:"started_at"`
	LastSpanAt     time.Time      `json:"last_span_at"`
	ClosedAt       sql.NullTime   `json:"closed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ApiKeyName     string         `json:"api_key_name"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID, arg.OrganizationID)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ApiKeyID,
		&i.ExternalID,
		&i.AgentName,
		&i.Status,
		&i.Narrative,
		&i.TotalCostUsd,
		&i.SpanCount,
		&i.StartedAt,
		&i.LastSpanAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKeyName,
	)
	return i, err
}

const getSessionOrgID = `-- name: GetSessionOrgID :one
SELECT organization_id FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionOrgID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionOrgID, id)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getSessionTimeoutForOrg = `-- name: GetSessionTimeoutForOrg :one
SELECT session_timeout_seconds FROM organizations WHERE id = $1
`

func (q *Queries) GetSessionTimeoutForOrg(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getSessionTimeoutForOrg, id)
	var session_timeout_seconds int32
	err := row.Scan(&session_timeout_seconds)
	return session_timeout_seconds, err
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.organization_id, s.api_key_id, s.external_id, s.agent_name,
       s.status, s.total_cost_usd, s.span_count,
       s.started_at, s.last_span_at, s.closed_at, s.created_at, s.updated_at,
       k.name AS api_key_name
FROM sessions s
JOIN api_keys k ON k.id = s.api_key_id
WHERE s.organization_id = $1
  AND ($2::timestamptz IS NULL
       OR s.started_at < $2
       OR (s.started_at = $2 AND s.id < $3::uuid))
  AND ($4::text IS NULL OR s.status = $4)
  AND ($5::uuid IS NULL OR s.api_key_id = $5)
  AND ($6::text IS NULL OR s.agent_name = $6)
  AND ($7::timestamptz IS NULL OR s.started_at >= $7)
  AND ($8::timestamptz IS NULL OR s.started_at <= $8)
  AND ($9::text IS NULL
       OR EXISTS (SELECT 1 FROM spans WHERE spans.session_id = s.id AND spans.provider_type = $9))
ORDER BY s.started_at DESC, s.id DESC
LIMIT $10
`

type ListSessionsParams struct {
	OrgID           uuid.UUID    `json:"org_id"`
	CursorStartedAt sql.NullTime `json:"cursor_started_at"`
	CursorID        pgtype.UUID  `json:"cursor_id"`
	Status          *string      `json:"status"`
	ApiKeyID        pgtype.UUID  `json:"api_key_id"`
	AgentName       *string      `json:"agent_name"`
	FromTime        sql.NullTime `json:"from_time"`
	ToTime          sql.NullTime `json:"to_time"`
	ProviderType    *string      `json:"provider_type"`
	PageLimit       int32        `json:"page_limit"`
}

type ListSessionsRow struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	ApiKeyID       uuid.UUID      `json:"api_key_id"`
	ExternalID     *string        `json:"external_id"`
	AgentName      *string        `json:"agent_name"`
	Status         string         `json:"status"`
	TotalCostUsd   pgtype.Numeric `json:"total_cost_usd"`
	SpanCount      int32          `json:"span_count"`
	StartedAt      time.Time      `json:"started_at"`
	LastSpanAt     time.Time      `json:"last_span_at"`
	ClosedAt       sql.NullTime   `json:"closed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ApiKeyName     string         `json:"api_key_name"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.OrgID,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.Status,
		arg.ApiKeyID,
		arg.AgentName,
		arg.FromTime,
		arg.ToTime,
		arg.ProviderType,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ApiKeyID,
			&i.ExternalID,
			&i.AgentName,
			&i.Status,
			&i.TotalCostUsd,
			&i.SpanCount,
			&i.StartedAt,
			&i.LastSpanAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApiKeyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAfterSpan = `-- name: UpdateSessionAfterSpan :exec
UPDATE sessions
SET span_count = span_count + 1,
    last_span_at = NOW(),
    total_cost_usd = total_cost_usd + $2::numeric(12,8),
    updated_at = NOW()
WHERE id = $1
`

type UpdateSessionAfterSpanParams struct {
	ID      uuid.UUID      `json:"id"`
	CostUsd pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) UpdateSessionAfterSpan(ctx context.Context, arg UpdateSessionAfterSpanParams) error {
	_, err := q.db.Exec(ctx, updateSessionAfterSpan, arg.ID, arg.CostUsd)
	return err
}
