// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countErrorSpansForSessions = `-- name: CountErrorSpansForSessions :many
SELECT session_id, COUNT(*) AS error_count
FROM spans
WHERE session_id = ANY($1::uuid[])
  AND http_status >= 400
GROUP BY session_id
`

type CountErrorSpansForSessionsRow struct {
	SessionID  uuid.UUID `json:"session_id"`
	ErrorCount int64     `json:"error_count"`
}

func (q *Queries) CountErrorSpansForSessions(ctx context.Context, sessionIds []uuid.UUID) ([]CountErrorSpansForSessionsRow, error) {
	rows, err := q.db.Query(ctx, countErrorSpansForSessions, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountErrorSpansForSessionsRow{}
	for rows.Next() {
		var i CountErrorSpansForSessionsRow
		if err := rows.Scan(&i.SessionID, &i.ErrorCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpansThisMonth = `-- name: CountSpansThisMonth :one
SELECT COUNT(*) FROM spans
WHERE organization_id = $1 AND created_at >= date_trunc('month', NOW())
`

func (q *Queries) CountSpansThisMonth(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSpansThisMonth, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgentStats = `-- name: GetAgentStats :many
SELECT
    ak.id AS api_key_id,
    ak.name AS api_key_name,
    COUNT(DISTINCT s.id) AS session_count,
    COUNT(sp.id) AS span_count,
    COALESCE(SUM(sp.cost_usd), 0)::numeric(12,8) AS total_cost_usd,
    COALESCE(AVG(sp.duration_ms), 0)::float8 AS avg_duration_ms,
    CASE WHEN COUNT(sp.id) > 0
         THEN COUNT(sp.id) FILTER (WHERE sp.http_status >= 400)::float8 / COUNT(sp.id)::float8
         ELSE 0::float8
    END AS error_rate,
    COALESCE(AVG(
        CASE WHEN sp.input_tokens > 0 AND sp.output_tokens IS NOT NULL
             THEN sp.output_tokens::float8 / sp.input_tokens::float8
        END
    ), 0)::float8 AS avg_token_ratio
FROM api_keys ak
JOIN sessions s ON s.api_key_id = ak.id
LEFT JOIN spans sp ON sp.session_id = s.id
WHERE ak.organization_id = $1
  AND s.started_at >= $2
  AND s.started_at <= $3
GROUP BY ak.id, ak.name
ORDER BY span_count DESC
`

type GetAgentStatsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

type GetAgentStatsRow struct {
	ApiKeyID      uuid.UUID      `json:"api_key_id"`
	ApiKeyName    string         `json:"api_key_name"`
	SessionCount  int64          `json:"session_count"`
	SpanCount     int64          `json:"span_count"`
	TotalCostUsd  pgtype.Numeric `json:"total_cost_usd"`
	AvgDurationMs float64        `json:"avg_duration_ms"`
	ErrorRate     float64        `json:"error_rate"`
	AvgTokenRatio float64        `json:"avg_token_ratio"`
}

func (q *Queries) GetAgentStats(ctx context.Context, arg GetAgentStatsParams) ([]GetAgentStatsRow, error) {
	rows, err := q.db.Query(ctx, getAgentStats, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentStatsRow{}
	for rows.Next() {
		var i GetAgentStatsRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.ApiKeyName,
			&i.SessionCount,
			&i.SpanCount,
			&i.TotalCostUsd,
			&i.AvgDurationMs,
			&i.ErrorRate,
			&i.AvgTokenRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishReasonDistribution = `-- name: GetFinishReasonDistribution :many
SELECT
    COALESCE(sp.finish_reason, 'unknown') AS finish_reason,
    COUNT(*) AS count
FROM spans sp
JOIN sessions s ON s.id = sp.session_id
WHERE s.organization_id = $1
  AND s.started_at >= $2
  AND s.started_at <= $3
GROUP BY 1
ORDER BY count DESC
`

type GetFinishReasonDistributionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

type GetFinishReasonDistributionRow struct {
	FinishReason string `json:"finish_reason"`
	Count        int64  `json:"count"`
}

func (q *Queries) GetFinishReasonDistribution(ctx context.Context, arg GetFinishReasonDistributionParams) ([]GetFinishReasonDistributionRow, error) {
	rows, err := q.db.Query(ctx, getFinishReasonDistribution, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinishReasonDistributionRow{}
	for rows.Next() {
		var i GetFinishReasonDistributionRow
		if err := rows.Scan(&i.FinishReason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelPrice = `-- name: GetModelPrice :one
SELECT input_price_per_token, output_price_per_token
FROM model_prices
WHERE provider_type = $1 AND model = $2
`

type GetModelPriceParams struct {
	ProviderType string `json:"provider_type"`
	Model        string `json:"model"`
}

type GetModelPriceRow struct {
	InputPricePerToken  pgtype.Numeric `json:"input_price_per_token"`
	OutputPricePerToken pgtype.Numeric `json:"output_price_per_token"`
}

func (q *Queries) GetModelPrice(ctx context.Context, arg GetModelPriceParams) (GetModelPriceRow, error) {
	row := q.db.QueryRow(ctx, getModelPrice, arg.ProviderType, arg.Model)
	var i GetModelPriceRow
	err := row.Scan(&i.InputPricePerToken, &i.OutputPricePerToken)
	return i, err
}

const getOrgDailyStats = `-- name: GetOrgDailyStats :many
SELECT
    date_trunc('day', s.started_at)::date AS day,
    COUNT(DISTINCT s.id) AS session_count,
    COUNT(sp.id) AS span_count,
    COALESCE(SUM(sp.cost_usd), 0)::numeric(12,8) AS cost_usd
FROM sessions s
LEFT JOIN spans sp ON sp.session_id = s.id
WHERE s.organization_id = $1
  AND s.started_at >= NOW() - ($2::int * interval '1 day')
GROUP BY 1
ORDER BY 1 ASC
`

type GetOrgDailyStatsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Days           int32     `json:"days"`
}

type GetOrgDailyStatsRow struct {
	Day          pgtype.Date    `json:"day"`
	SessionCount int64          `json:"session_count"`
	SpanCount    int64          `json:"span_count"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) GetOrgDailyStats(ctx context.Context, arg GetOrgDailyStatsParams) ([]GetOrgDailyStatsRow, error) {
	rows, err := q.db.Query(ctx, getOrgDailyStats, arg.OrganizationID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgDailyStatsRow{}
	for rows.Next() {
		var i GetOrgDailyStatsRow
		if err := rows.Scan(
			&i.Day,
			&i.SessionCount,
			&i.SpanCount,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgStats = `-- name: GetOrgStats :one
SELECT
    COUNT(DISTINCT s.id) AS total_sessions,
    COUNT(sp.id) AS total_spans,
    COALESCE(SUM(sp.cost_usd), 0)::numeric(12,8) AS total_cost_usd,
    COALESCE(AVG(sp.duration_ms), 0)::float8 AS avg_duration_ms,
    CASE WHEN COUNT(sp.id) > 0
         THEN COUNT(sp.id) FILTER (WHERE sp.http_status >= 400)::float8 / COUNT(sp.id)::float8
         ELSE 0::float8
    END AS error_rate
FROM sessions s
LEFT JOIN spans sp ON sp.session_id = s.id
WHERE s.organization_id = $1
  AND s.started_at >= $2
  AND s.started_at <= $3
`

type GetOrgStatsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

type GetOrgStatsRow struct {
	TotalSessions int64          `json:"total_sessions"`
	TotalSpans    int64          `json:"total_spans"`
	TotalCostUsd  pgtype.Numeric `json:"total_cost_usd"`
	AvgDurationMs float64        `json:"avg_duration_ms"`
	ErrorRate     float64        `json:"error_rate"`
}

func (q *Queries) GetOrgStats(ctx context.Context, arg GetOrgStatsParams) (GetOrgStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrgStats, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var i GetOrgStatsRow
	err := row.Scan(
		&i.TotalSessions,
		&i.TotalSpans,
		&i.TotalCostUsd,
		&i.AvgDurationMs,
		&i.ErrorRate,
	)
	return i, err
}

const getSpansBySessionID = `-- name: GetSpansBySessionID :many
SELECT id, session_id, organization_id, provider_type, model,
       input, output, input_tokens, output_tokens,
       cost_usd, duration_ms, http_status, started_at, created_at,
       finish_reason, masking_applied
FROM spans
WHERE session_id = $1 AND organization_id = $2
ORDER BY created_at ASC
`

type GetSpansBySessionIDParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetSpansBySessionID(ctx context.Context, arg GetSpansBySessionIDParams) ([]Span, error) {
	rows, err := q.db.Query(ctx, getSpansBySessionID, arg.SessionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Span{}
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OrganizationID,
			&i.ProviderType,
			&i.Model,
			&i.Input,
			&i.Output,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.HttpStatus,
			&i.StartedAt,
			&i.CreatedAt,
			&i.FinishReason,
			&i.MaskingApplied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSpan = `-- name: InsertSpan :one
INSERT INTO spans (
    session_id, organization_id, provider_type, model,
    input, output, input_tokens, output_tokens,
    cost_usd, duration_ms, http_status, started_at, finish_reason,
    masking_applied
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type InsertSpanParams struct {
	SessionID      uuid.UUID      `json:"session_id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	ProviderType   string         `json:"provider_type"`
	Model          string         `json:"model"`
	Input          *string        `json:"input"`
	Output         *string        `json:"output"`
	InputTokens    *int32         `json:"input_tokens"`
	OutputTokens   *int32         `json:"output_tokens"`
	CostUsd        pgtype.Numeric `json:"cost_usd"`
	DurationMs     int32          `json:"duration_ms"`
	HttpStatus     int32          `json:"http_status"`
	StartedAt      time.Time      `json:"started_at"`
	FinishReason   string         `json:"finish_reason"`
	MaskingApplied bool           `json:"masking_applied"`
}

func (q *Queries) InsertSpan(ctx context.Context, arg InsertSpanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSpan,
		arg.SessionID,
		arg.OrganizationID,
		arg.ProviderType,
		arg.Model,
		arg.Input,
		arg.Output,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.DurationMs,
		arg.HttpStatus,
		arg.StartedAt,
		arg.FinishReason,
		arg.MaskingApplied,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const purgeOldAlertEvents = `-- name: PurgeOldAlertEvents :execrows
DELETE FROM alert_events
WHERE id IN (
    SELECT id FROM alert_events
    WHERE triggered_at < NOW() - ($1::int * interval '1 day')
    LIMIT $2
)
`

type PurgeOldAlertEventsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) PurgeOldAlertEvents(ctx context.Context, arg PurgeOldAlertEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldAlertEvents, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldSessions = `-- name: PurgeOldSessions :execrows
DELETE FROM sessions
WHERE id IN (
    SELECT id FROM sessions
    WHERE closed_at IS NOT NULL
      AND closed_at < NOW() - ($1::int * interval '1 day')
      AND NOT EXISTS (SELECT 1 FROM spans WHERE spans.session_id = sessions.id)
    LIMIT $2
)
`

type PurgeOldSessionsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) PurgeOldSessions(ctx context.Context, arg PurgeOldSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldSessions, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldSpans = `-- name: PurgeOldSpans :execrows
DELETE FROM spans
WHERE id IN (
    SELECT id FROM spans
    WHERE created_at < NOW() - ($1::int * interval '1 day')
    LIMIT $2
)
`

type PurgeOldSpansParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) PurgeOldSpans(ctx context.Context, arg PurgeOldSpansParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldSpans, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
