// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_prompts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSystemPromptsForOrg = `-- name: CountSystemPromptsForOrg :one
SELECT COUNT(*) FROM system_prompts WHERE organization_id = $1
`

func (q *Queries) CountSystemPromptsForOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemPromptsForOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findOrCreateSystemPrompt = `-- name: FindOrCreateSystemPrompt :one
INSERT INTO system_prompts (organization_id, content, content_hash, short_uid)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id, content_hash)
DO UPDATE SET created_at = system_prompts.created_at
RETURNING id, organization_id, content, content_hash, short_uid, created_at
`

type FindOrCreateSystemPromptParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Content        string    `json:"content"`
	ContentHash    string    `json:"content_hash"`
	ShortUid       string    `json:"short_uid"`
}

func (q *Queries) FindOrCreateSystemPrompt(ctx context.Context, arg FindOrCreateSystemPromptParams) (SystemPrompt, error) {
	row := q.db.QueryRow(ctx, findOrCreateSystemPrompt,
		arg.OrganizationID,
		arg.Content,
		arg.ContentHash,
		arg.ShortUid,
	)
	var i SystemPrompt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Content,
		&i.ContentHash,
		&i.ShortUid,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemPromptByID = `-- name: GetSystemPromptByID :one
SELECT
    sp.id,
    sp.short_uid,
    sp.content,
    sp.content_hash,
    sp.created_at,
    COUNT(DISTINCT ssp.span_id)::int AS span_count,
    COUNT(DISTINCT s.session_id)::int AS session_count,
    MAX(s.created_at)::timestamptz AS last_seen_at
FROM system_prompts sp
LEFT JOIN span_system_prompts ssp ON ssp.system_prompt_id = sp.id
LEFT JOIN spans s ON s.id = ssp.span_id
WHERE sp.id = $1 AND sp.organization_id = $2
GROUP BY sp.id
`

type GetSystemPromptByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetSystemPromptByIDRow struct {
	ID           uuid.UUID `json:"id"`
	ShortUid     string    `json:"short_uid"`
	Content      string    `json:"content"`
	ContentHash  string    `json:"content_hash"`
	CreatedAt    time.Time `json:"created_at"`
	SpanCount    int32     `json:"span_count"`
	SessionCount int32     `json:"session_count"`
	LastSeenAt   time.Time `json:"last_seen_at"`
}

func (q *Queries) GetSystemPromptByID(ctx context.Context, arg GetSystemPromptByIDParams) (GetSystemPromptByIDRow, error) {
	row := q.db.QueryRow(ctx, getSystemPromptByID, arg.ID, arg.OrganizationID)
	var i GetSystemPromptByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShortUid,
		&i.Content,
		&i.ContentHash,
		&i.CreatedAt,
		&i.SpanCount,
		&i.SessionCount,
		&i.LastSeenAt,
	)
	return i, err
}

const insertSpanSystemPrompt = `-- name: InsertSpanSystemPrompt :exec
INSERT INTO span_system_prompts (span_id, system_prompt_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSpanSystemPromptParams struct {
	SpanID         uuid.UUID `json:"span_id"`
	SystemPromptID uuid.UUID `json:"system_prompt_id"`
}

func (q *Queries) InsertSpanSystemPrompt(ctx context.Context, arg InsertSpanSystemPromptParams) error {
	_, err := q.db.Exec(ctx, insertSpanSystemPrompt, arg.SpanID, arg.SystemPromptID)
	return err
}

const listSystemPrompts = `-- name: ListSystemPrompts :many
SELECT
    sp.id,
    sp.short_uid,
    sp.content_hash,
    length(sp.content)::int AS content_length,
    left(sp.content, 200) AS content_preview,
    sp.created_at,
    COUNT(DISTINCT ssp.span_id)::int AS span_count,
    COUNT(DISTINCT s.session_id)::int AS session_count,
    MAX(s.created_at)::timestamptz AS last_seen_at
FROM system_prompts sp
LEFT JOIN span_system_prompts ssp ON ssp.system_prompt_id = sp.id
LEFT JOIN spans s ON s.id = ssp.span_id
WHERE sp.organization_id = $1
GROUP BY sp.id
ORDER BY sp.created_at DESC
`

type ListSystemPromptsRow struct {
	ID             uuid.UUID `json:"id"`
	ShortUid       string    `json:"short_uid"`
	ContentHash    string    `json:"content_hash"`
	ContentLength  int32     `json:"content_length"`
	ContentPreview string    `json:"content_preview"`
	CreatedAt      time.Time `json:"created_at"`
	SpanCount      int32     `json:"span_count"`
	SessionCount   int32     `json:"session_count"`
	LastSeenAt     time.Time `json:"last_seen_at"`
}

func (q *Queries) ListSystemPrompts(ctx context.Context, organizationID uuid.UUID) ([]ListSystemPromptsRow, error) {
	rows, err := q.db.Query(ctx, listSystemPrompts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemPromptsRow{}
	for rows.Next() {
		var i ListSystemPromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortUid,
			&i.ContentHash,
			&i.ContentLength,
			&i.ContentPreview,
			&i.CreatedAt,
			&i.SpanCount,
			&i.SessionCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSpanInputPrefix = `-- name: ReplaceSpanInputPrefix :exec
UPDATE spans
SET input = $1 || substring(input FROM length($2::text) + 1)
WHERE id = $3::uuid AND organization_id = $4::uuid AND input IS NOT NULL AND starts_with(input, $2::text)
`

type ReplaceSpanInputPrefixParams struct {
	Replacement    *string   `json:"replacement"`
	OldPrefix      string    `json:"old_prefix"`
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ReplaceSpanInputPrefix(ctx context.Context, arg ReplaceSpanInputPrefixParams) error {
	_, err := q.db.Exec(ctx, replaceSpanInputPrefix,
		arg.Replacement,
		arg.OldPrefix,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
