// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at, password_changed_at, accepted_terms_at, accepted_privacy_at, policy_version
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.AcceptedTermsAt,
		&i.AcceptedPrivacyAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, email_verified_at, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID    `json:"id"`
	Email           string       `json:"email"`
	Name            string       `json:"name"`
	PasswordHash    string       `json:"password_hash"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, email_verified_at, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID              uuid.UUID    `json:"id"`
	Email           string       `json:"email"`
	Name            string       `json:"name"`
	PasswordHash    string       `json:"password_hash"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordChangedAt = `-- name: GetUserPasswordChangedAt :one
SELECT password_changed_at FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordChangedAt(ctx context.Context, id uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRow(ctx, getUserPasswordChangedAt, id)
	var password_changed_at sql.NullTime
	err := row.Scan(&password_changed_at)
	return password_changed_at, err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}

const setUserTermsAccepted = `-- name: SetUserTermsAccepted :exec
UPDATE users
SET accepted_terms_at = NOW(), accepted_privacy_at = NOW(), policy_version = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserTermsAcceptedParams struct {
	ID            uuid.UUID `json:"id"`
	PolicyVersion int32     `json:"policy_version"`
}

func (q *Queries) SetUserTermsAccepted(ctx context.Context, arg SetUserTermsAcceptedParams) error {
	_, err := q.db.Exec(ctx, setUserTermsAccepted, arg.ID, arg.PolicyVersion)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $1, email_verified_at = NULL, updated_at = NOW() WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $1, updated_at = NOW() WHERE id = $2
`

type UpdateUserNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.Name, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, password_changed_at = NOW(), updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
