package metrics

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	// HTTP API metrics
	HTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_http_requests_total",
		Help: "Total HTTP requests by method, path pattern, and status code.",
	}, []string{"method", "route", "status"})

	HTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "agentspan_processing_http_request_duration_seconds",
		Help:    "HTTP request duration in seconds.",
		Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
	}, []string{"method", "route"})

	// Database pool metrics
	DBPoolActiveConns = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_db_pool_active_conns",
		Help: "Current number of active database connections.",
	})

	DBPoolIdleConns = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_db_pool_idle_conns",
		Help: "Current number of idle database connections.",
	})

	DBPoolTotalConns = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_db_pool_total_conns",
		Help: "Current total database connections in the pool.",
	})

	DBPoolMaxConns = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_db_pool_max_conns",
		Help: "Maximum database connections configured.",
	})

	// Internal API metrics (Proxy -> Processing)
	InternalSpansIngested = promauto.NewCounter(prometheus.CounterOpts{
		Name: "agentspan_processing_internal_spans_ingested_total",
		Help: "Total spans ingested from proxy.",
	})

	InternalAuthVerifications = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_internal_auth_verifications_total",
		Help: "Total auth verification requests by result (valid, invalid, error).",
	}, []string{"result"})

	// WebSocket metrics
	WSActiveConnections = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_ws_active_connections",
		Help: "Current number of active WebSocket connections.",
	})

	WSMessagesPublished = promauto.NewCounter(prometheus.CounterOpts{
		Name: "agentspan_processing_ws_messages_published_total",
		Help: "Total WebSocket messages published to clients.",
	})

	// Session metrics
	SessionsClosed = promauto.NewCounter(prometheus.CounterOpts{
		Name: "agentspan_processing_sessions_closed_total",
		Help: "Total sessions closed by the session closure cron.",
	})

	SessionsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "agentspan_processing_sessions_active",
		Help: "Current number of active (non-closed) sessions.",
	})

	// Intelligence pipeline metrics
	NarrativesGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_narratives_generated_total",
		Help: "Total narratives generated by method (llm, concat).",
	}, []string{"method"})

	ClassificationsRun = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_classifications_total",
		Help: "Total classification runs by type (failure_cluster, request_category).",
	}, []string{"type"})

	// Alert metrics
	AlertsEvaluated = promauto.NewCounter(prometheus.CounterOpts{
		Name: "agentspan_processing_alerts_evaluated_total",
		Help: "Total alert rule evaluations.",
	})

	AlertsFired = promauto.NewCounter(prometheus.CounterOpts{
		Name: "agentspan_processing_alerts_fired_total",
		Help: "Total alert events triggered.",
	})

	// Worker metrics
	WorkerQueueDepth = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "agentspan_processing_worker_queue_depth",
		Help: "Current depth of async worker queues.",
	}, []string{"worker"})

	WorkerTaskDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "agentspan_processing_worker_task_duration_seconds",
		Help:    "Duration of async worker task execution.",
		Buckets: []float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30},
	}, []string{"worker"})

	// Data retention
	RetentionPurgedRows = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_retention_purged_rows_total",
		Help: "Total rows purged by data retention cron.",
	}, []string{"table"})

	// Cron metrics
	CronRunsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "agentspan_processing_cron_runs_total",
		Help: "Total cron job executions by job name and result.",
	}, []string{"job", "result"})

	CronDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "agentspan_processing_cron_duration_seconds",
		Help:    "Cron job execution duration.",
		Buckets: []float64{0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30},
	}, []string{"job"})
)

// Handler returns the Prometheus HTTP handler for the /metrics endpoint.
func Handler() http.Handler {
	return promhttp.Handler()
}

// ObserveHTTPRequest records HTTP request metrics.
func ObserveHTTPRequest(method, route string, statusCode int, duration time.Duration) {
	status := strconv.Itoa(statusCode)
	HTTPRequestsTotal.WithLabelValues(method, route, status).Inc()
	HTTPRequestDuration.WithLabelValues(method, route).Observe(duration.Seconds())
}
